apiVersion: v1
kind: PersistentVolume 
metadata:
  labels:
    storage: nfs
  name: meu-pv-nfs
spec: 
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce                         #Tem leitura e escrita porém apartir de 1 unico nó (padrão maioria das vezes)
  persistentVolumeReclaimPolicy: Retain 
  nfs:                                      #informando que é nfs
    server: 192.168.195.84                  #ip do servidor que está compartilhando o diretório abaixo
    path: "/mnt/nfs"                        #diretório compartilhado
  storageClassName: giropops                #Nome do StorageClasse