version: "3.8"
services:
  giropops-senhas:
    image: rodrigocorazza/giropops-senhas:latest
    ports: 
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
    env_file:
      - .env
    volumes:
      - type: volume
        source: strigus 
        target: /strigus
    depends_on:
      - redis
    labels:
      com.docker.description: "Giropops"
    deploy:
      resources:
        reservations:
          cpus: '0.2'
          memory: '128M'
        limits:                           #limits: limite maximo que o container pode usar
          cpus: '0.5'                     
          memory: '256M'  
      restart_policy:
        condition: on-failure 
        delay: 5s
        max_attempts: 3

  redis:
    image: redis
    networks:
      - giropops
    volumes:
      - strigus:/strigus 

networks:
  giropops:
    driver: bridge

volumes:
  strigus:  
    driver: local
