version: "3"
services:
  giropops-senhas:
    build: ./
    ports:
      - "80:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
    volumes:
      - strigus:/strigus

  redis:
    image: redis
    networks:
      - giropops
    volumes:
      - strigus:/strigus

networks:
  giropops:
    driver: bridge

volumes:
  strigus: 
