apiVersion: v1 
kind: Service 
metadata:
  labels:
    app: giropops-senhas
  name: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: tcp-app
  type: ClusterIP 
