apiVersion: v1 
kind: Secret 
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson #Este é o tipo de Secret. Este tipo específico é usado para autenticar com um registro de contêiner Docker.
data:
  .dockerconfigjson: |   #Campo de dados que contém as informações de autenticação para o Docker.
    ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRo
    IjogImNtOWtjbWxuYjJOdmNtRjZlbUU2WkdOcmNsOXdZWFJmV0VSUmRYbElhWEJaTm1kbmFHNUNl
    VFJqZW1sWGExWmpRMUJ2IgoJCX0KCX0KfQ==

  #Usar o pipe permite que você quebre essa string longa em várias linhas para melhor legibilidade, sem alterar o valor da string.

