FROM ubuntu:20.04
ENV REDIS_HOST=localhost
RUN apt-get update && apt-get install -y \
    python3.8 \
    pip \
    git  

RUN git clone https://github.com/badtuxx/giropops-senhas.git /app/giropops-senhas
WORKDIR /app/giropops-senhas/
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install Werkzeug==2.2.2
EXPOSE 5000
ENTRYPOINT ["flask"]
CMD ["run", "--host=0.0.0.0"]


#Testar multistage com alpine