apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-prometheus-rule
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
spec:
  groups:
  - name: nginx-prometheus-rule
    rules:
    - alert: NginxDown
      expr: nginx_up == 0
      for: 1m
      labels:
        severity: critical
      annotations: 
        summary: "Nginx is down"
        description: "Nginx is down for more than 1 minute"
    - alert: NginxHightRequestRate
      expr: rate(nginx_http_requests_total[1m]) > 10
      for: 1m
      labels:
        severity: warning
      annotations: 
        summary: "Nginx is receiving a high request rate"
        description: "Nginx is receiving more than 10 requests per minute"
