apiVersion: kyverno.io/v1
kind: ClusterPolicy #ClusterPolicy se aplica a todos os namespaces /Policy que se aplica a um namespace
metadata:
  name: add-label-namespace
spec:
  rules: 
  - name: add-label-ns 
    match:
      resources: 
        kinds:
        - Namespace 
    mutate:
      patchStrategicMerge: #estratégica de merge de modificações, vai adicionar o label no namespace
        metadata: 
          labels: 
            rodrigo: "rodrigo_corazza"
