apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: ensure-images-from-trusted-registry
  namespace: giropops 
spec: 
  validationFailureAction: Enforce
  rules: 
    - name: trusted-registry 
      match:
        resources:
          kinds:
          - Pod
      validate:
        message: "Somente images do repo da Chainguard são permitidas"
        pattern:
          spec:
            containers:
            - name: "*"
              image: "cgr.dev/chainguard/*" #vai verificar se a imagem é do repo da Chainguard, ex: cgr.dev/chainguard/nginx:latest