apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  ports:
    - name: http
      nodePort: 32500
      port: 80
      targetPort: 5000 
  type: NodePort

#O nodePort é a porta que o serviço vai escutar no node, no caso 32500 e vai redirecionar para a porta 80 do pod.
#o port é a porta que o serviço vai escutar, no caso 80, que é a porta padrão do protocolo http e vai redirecionar para a porta 5000 do pod.
#O targetPort faz referência a porta que o pod está escutando, no caso 5000, que é a mesma porta do pod do deployment.
