apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:             #volumeMounts: Definindo o volume dentro do container
    - mountPath: /giropops    #mountPath: Lugar de onde o volume vai ficar montado
      name: primeiro-empydir  #name: mesmo nome do volume criado la embaixo
    resources: 
      limits:                
        cpu: "1"
        memory: "128Mi"
      requests:              
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:                    #cria-se a definição do volume primeiro para depois especificar la em cima dentro do container
  - name: primeiro-empydir
    emptyDir:                 #emptyDir: Volume do diretório vazio
      sizeLimit: 256Mi


