apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args: 
    - sleep 
    - "1800"
    resources: 
      limits:                #Limite maximo do uso quatidade de recurso operacional
        cpu: "0.5"
        memory: "128Mi"
      requests:              #request ja garante uma quantidade de recurso operacional, reservado
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
